pwd

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/satya/Desktop/PFSD_project/dataset/INvideos.csv', encoding="ISO-8859-1")

In [4]:
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12T12:20:39.000Z,"sharry mann|""sharry mann new song""|""sharry man...",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,False,False,False,Presenting Sharry Mann latest Punjabi Song Cu...
1,zUZ1z7FwLc8,17.14.11,"à¤ªà¥à¤°à¤¿à¤¯à¤¡à¥à¤¸ à¤à¥ à¤¸à¤®à¤¯, à¤ª...",HJ NEWS,25,2017-11-13T05:43:56.000Z,"à¤ªà¥à¤°à¤¿à¤¯à¤¡à¥à¤¸ à¤à¥ à¤¸à¤®à¤¯|""à¤ª...",590101,735,904,0,https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg,True,False,False,"à¤ªà¥à¤°à¤¿à¤¯à¤¡à¥à¤¸ à¤à¥ à¤¸à¤®à¤¯, à¤ª..."
2,10L1hZ9qa58,17.14.11,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12T15:48:08.000Z,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,473988,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,False,False,False,Watch Stylish Star Allu Arjun @ ChaySam Weddin...
3,N1vE8iiEg64,17.14.11,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12T07:08:48.000Z,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",1242680,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,False,False,False,This video showcases the difference between pe...
4,kJzGH0PVQHQ,17.14.11,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13T01:14:16.000Z,"Filmylooks|""latest news""|""telugu movies""|""telu...",464015,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,False,False,False,why Samantha became EMOTIONAL @ Samantha naga ...

In [5]:
df.shape

(37352, 16)

In [6]:
import numpy as np

In [7]:
df.describe()

        category_id         views         likes      dislikes  comment_count
count  37352.000000  3.735200e+04  3.735200e+04  3.735200e+04    37352.00000
mean      21.576596  1.060478e+06  2.708272e+04  1.665082e+03     2676.99743
std        6.556593  3.184932e+06  9.714510e+04  1.607617e+04    14868.31713
min        1.000000  4.024000e+03  0.000000e+00  0.000000e+00        0.00000
25%       23.000000  1.239155e+05  8.640000e+02  1.080000e+02       81.00000
50%       24.000000  3.045860e+05  3.069000e+03  3.260000e+02      329.00000
75%       24.000000  7.992912e+05  1.377425e+04  1.019250e+03     1285.00000
max       43.000000  1.254322e+08  2.912710e+06  1.545017e+06   827755.00000

In [8]:
df['log_views']=np.log(df['views'])
df['log_likes']=np.log(df['likes'])

C:\Users\satya\anaconda3\lib\site-packages\pandas\core\arraylike.py:364: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [9]:
from bokeh.plotting import figure,output_file, show
from bokeh.models import ColumnDataSource
from bokeh.models.tools import HoverTool

In [10]:
fig=figure(tooltips=TOOLTIPS)
p=fig.circle(x='likes',y='views',source=df)

NameError: name 'TOOLTIPS' is not defined

In [11]:
#tooltips
TOOLTIPS = [
    ("Title","@title"),
    ("Channel","@channel_title"),
    ("Views","@views"),
]
fig = figure(tooltips=TOOLTIPS)
p = fig.circle(x='log_likes', y='log_views', source=df)

fig.xaxis.axis_label = 'Likes'
fig.yaxis.axis_label = 'views'
glyph = p.glyph
glyph.size = 10
glyph.fill_alpha = 0.2
glyph.fill_color = "#ADD8E6"
glyph.line_color = "grey"
glyph.line_dash = [6,3]
glyph.line_width = 2

In [12]:
show(fig)

In [24]:
df.groupby('category_id').count()

,video_id,trending_date,title,channel_title,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,log_views,log_likes
category_id,,,,,,,,,,,,,,,,,
1,2060,2060,2060,2060,2060,2060,2060,2060,2060,2060,2060,2060,2060,2060,2001,2060,2060
2,353,353,353,353,353,353,353,353,353,353,353,353,353,353,348,353,353
10,3731,3731,3731,3731,3731,3731,3731,3731,3731,3731,3731,3731,3731,3731,3695,3731,3731
15,369,369,369,369,369,369,369,369,369,369,369,369,369,369,369,369,369
17,2787,2787,2787,2787,2787,2787,2787,2787,2787,2787,2787,2787,2787,2787,2650,2787,2787
19,392,392,392,392,392,392,392,392,392,392,392,392,392,392,377,392,392
20,1344,1344,1344,1344,1344,1344,1344,1344,1344,1344,1344,1344,1344,1344,1330,1344,1344
22,4105,4105,4105,4105,4105,4105,4105,4105,4105,4105,4105,4105,4105,4105,3726,4105,4105
23,3773,3773,3773,3773,3773,3773,3773,3773,3773,3773,3773,3773,3773,3773,3725,3773,3773
24,13451,13451,13451,13451,13451,13451,13451,13451,13451,13451,13451,13451,13451,13451,13173,13451,13451
25,4159,4159,4159,4159,4159,4159,4159,4159,4159,4159,4159,4159,4159,4159,3868,4159,4159
26,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,1998,2007,2007
27,991,991,991,991,991,991,991,991,991,991,991,991,991,991,982,991,991
28,1155,1155,1155,1155,1155,1155,1155,1155,1155,1155,1155,1155,1155,1155,1143,1155,1155
29,74,74,74,74,74,74,74,74,74,74,74,74,74,74,70,74,74
30,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
43,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124

In [25]:
entertatinment = df[df['category_id'] == 24 ]

In [26]:
entertatinment.sort_values('views', ascending=False)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,log_views,log_likes
5900,FlsCjmMhFmw,17.13.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",137843120,3014479,1602383,817582,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",18.741627,14.918938
5623,FlsCjmMhFmw,17.12.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",125431369,2912715,1545018,807558,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",18.647269,14.884596
5398,FlsCjmMhFmw,17.11.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",113876217,2811217,1470387,787174,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",18.550623,14.849128
5197,FlsCjmMhFmw,17.10.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",100911567,2656678,1353655,682890,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",18.429755,14.792587
4699,6ZfuNTqbHE8,17.07.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29T13:26:24.000Z,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",89930713,2606665,53011,347982,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an ideaâ¦ Avengers: Infinity War. I...,18.314550,14.773582
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19937,wuF9_Jy7OfA,18.23.02,Marijuana Stocks Technical Analysis Chart 2/22...,TheChartGuys,24,2018-02-22T23:26:14.000Z,"trade|""stocks chart trading""|""technical analys...",1941,39,1,10,https://i.ytimg.com/vi/wuF9_Jy7OfA/default.jpg,False,False,False,NEW Crypto Alert System: https://crypto.chartg...,7.570959,3.663562
26046,yWp7YrLjoSQ,18.26.03,Debbie Lynch-White de ''UnitÃ© 9'' incarne ''L...,mart lat,24,2018-03-26T01:32:42.000Z,"Debbie Lynch-White|""La Bolduc""|""UnitÃ© 9""|""Tou...",1921,17,0,0,https://i.ytimg.com/vi/yWp7YrLjoSQ/default.jpg,False,False,False,En plongeant dans ses recherches pour incarner...,7.560601,2.833213
22721,s029voQMRzU,18.09.03,Marijuana Stocks Technical Analysis Chart 3/8/...,TheChartGuys,24,2018-03-09T01:12:35.000Z,"trade|""stocks chart trading""|""technical analys...",1542,35,0,6,https://i.ytimg.com/vi/s029voQMRzU/default.jpg,False,False,False,NEW Crypto Alert System: https://crypto.chartg...,7.340836,3.555348
20505,MTtFpn9C7Q4,18.26.02,Simon Olivier Fecteau crÃ©ateur des derniers B...,mart lat,24,2018-02-26T03:18:13.000Z,"Simon Olivier Fecteau|""Bye bye""|""En audition a...",1107,14,1,3,https://i.ytimg.com/vi/MTtFpn9C7Q4/default.jpg,False,False,False,Simon Olivier Fecteau renoue avec son ingrat p...,7.009409,2.639057
34625,bz91MAdY6FQ,18.14.05,''Gala Artis 2018'' Le numÃ©ro d'ouverture,mart lat,24,2018-05-14T00:43:35.000Z,"gala|""artis""|""2018""|""numÃ©ro d'ouverture""|""Yam...",733,10,4,0,https://i.ytimg.com/vi/bz91MAdY6FQ/default.jpg,False,False,False,Anim.: Maripier Morin et Jean-Philippe Dion. L...,6.597146,2.302585

In [ ]:
entertatinment.views.dtype

In [ ]:
entertatinment.describe()

In [11]:
pd.options.display.float_format = '{:,f}'.format
entertatinment[{'views','likes'}].describe()

NameError: name 'entertatinment' is not defined

In [30]:
show(fig.df['category_id'] == 24)

AttributeError: unexpected attribute 'df' to Figure, possible attributes are above, align, aspect_ratio, aspect_scale, background, background_fill_alpha, background_fill_color, below, border_fill_alpha, border_fill_color, center, css_classes, disabled, extra_x_ranges, extra_x_scales, extra_y_ranges, extra_y_scales, frame_height, frame_width, height, height_policy, hidpi, inner_height, inner_width, js_event_callbacks, js_property_callbacks, left, lod_factor, lod_interval, lod_threshold, lod_timeout, margin, match_aspect, max_height, max_width, min_border, min_border_bottom, min_border_left, min_border_right, min_border_top, min_height, min_width, name, outer_height, outer_width, outline_line_alpha, outline_line_cap, outline_line_color, outline_line_dash, outline_line_dash_offset, outline_line_join, outline_line_width, output_backend, plot_height, plot_width, renderers, reset_policy, right, sizing_mode, subscribed_events, syncable, tags, title, title_location, toolbar, toolbar_location, toolbar_sticky, visible, width, width_policy, x_range, x_scale, y_range or y_scale